version: "3.9"
services:
  web-app:
    build:
      context: ./Dockerfile
      dockerfile: rails-dev-env
    ports:
      - "8000:3000"
    volumes:
      - ./rails-app:/root/tutorial-app
    command: /bin/bash -c "source /usr/local/rvm/scripts/rvm && bundle install && rails server -p 3000"
    working_dir: /root/tutorial-app
    stdin_open: true
    tty: true
    depends_on:
      - database

  database:
    image:
      mysql:5.7
    volumes:
      - mysql-database:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

volumes:
  mysql-database:
